server:
  port: 8081

spring:
  # H2 Database 설정
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
      driver-class-name: org.h2.Driver
      url: jdbc:h2:mem:demo;NON_KEYWORDS=user
      username: sa
      password:
  ## JPA Setting Info
  jpa:
    hibernate:
      ddl-auto: create  # option type: create, create-drop, update, validate, none
    properties:
      hibernate:
        diarect: org.hibernate.dialect.H2Dialect  # 쿼리의 기준이 되는 데이터베이스 엔진을 설정합니다.
        show_sql: true  # sql 쿼리를 보여줍니다.
        format_sql: true  # sql query formatting
        use_sql_comments: true  # sql 쿼리의 추가정보를 보여줍니다.

logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace